name: spacex
description: Online Challenge @ Estatetial

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_widgets: ^0.1.7+1
  shared_preferences: any
  rxdart: ^0.24.1
  fluttertoast: ^3.1.0
  dio: ^3.0.9
  get_it: ^3.0.1
  flutter_bloc: ^4.0.1
  built_value: ^7.1.0
  analyzer: ^0.39.14
  flutter_spinkit: "^4.0.0"
  requests: ^3.3.0
  url_launcher: ^5.5.0
  floor: ^0.14.0
        # flutter_facebook_login:
        #   git:
      #     url: https://github.com/roughike/flutter_facebook_login
      #     ref: '79ff08a'
  firebase_messaging: ^5.1.8
  image_picker: ^0.6.7+4
  dio_cookie_manager: ^1.0.0
  rating_dialog: ^1.0.0
  page_transition: ^1.1.6
  flutter_country_picker: ^0.1.6
  flutter_rounded_date_picker: ^1.0.4
  awesome_dialog: ^1.2.0
  flutter_svg: ^0.19.0
  dropdown_search: ^0.4.4
  flutter_verification_code: ^0.2.1
  font_awesome_flutter: ^8.11.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
